name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Step 4: Set PYTHONPATH using environment file
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    # Step 5: Lint Code
    - name: Run Linter
      run: |
        pylint app.py

    # Step 6: Run Unit Tests
    - name: Run Tests
      run: |
        python -m unittest discover
